//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ma_win.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MA_WIN_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_VIDMODE                     129
#define IDD_ASSET_PICKER                130
#define IDD_INPUT_EMULATION             131
#define IDC_30FPS                       1000
#define IDC_3D_COLOR                    1001
#define IDC_60FPS                       1002
#define IDC_BUTTON_INPUT_EMULATION      1003
#define IDC_BUTTON_LOAD                 1004
#define IDC_BUTTON_RUN                  1005
#define IDC_CHECK_FULLSCREEN            1006
#define IDC_CHOOSE_MASTER_FILE          1007
#define IDC_CHOOSE_MEMCARD_DIR          1008
#define IDC_CHOOSE_SCREENSHOT_DIR       1009
#define IDC_COMBO_DEVICE                1010
#define IDC_COMBO_EMUL_DEVICES          1011
#define IDC_COMBO_EMUL_XB_RESET         1012
#define IDC_COMBO_EMUL_XB_START         1013
#define IDC_COMBO_EMUL_XB_BACK          1014
#define IDC_COMBO_EMUL_XB_BLACK         1015
#define IDC_COMBO_EMUL_XB_WHITE         1016
#define IDC_COMBO_EMUL_XB_A             1017
#define IDC_COMBO_EMUL_XB_B             1018
#define IDC_COMBO_EMUL_XB_X             1019
#define IDC_COMBO_EMUL_XB_Y             1020
#define IDC_COMBO_EMUL_XB_LEFT_TRIGGER  1021
#define IDC_COMBO_EMUL_XB_RIGHT_TRIGGER 1022
#define IDC_COMBO_EMUL_XB_LEFT_STICK    1023
#define IDC_COMBO_EMUL_XB_RIGHT_STICK   1024
#define IDC_COMBO_EMUL_GC_RESET         1025
#define IDC_COMBO_EMUL_GC_START         1026
#define IDC_COMBO_EMUL_GC_A             1027
#define IDC_COMBO_EMUL_GC_B             1028
#define IDC_COMBO_EMUL_GC_X             1029
#define IDC_COMBO_EMUL_GC_Y             1030
#define IDC_COMBO_EMUL_GC_Z             1031
#define IDC_COMBO_EMUL_GC_LEFT_TRIGGER_A 1032
#define IDC_COMBO_EMUL_GC_RIGHT_TRIGGER_A 1033
#define IDC_COMBO_EMUL_GC_RIGHT_TRIGGER_D 1034
#define IDC_COMBO_EMUL_GC_LEFT_TRIGGER_D 1035
#define IDC_COMBO_EMUL_XB_LEFT_STICK_X  1036
#define IDC_COMBO_EMUL_XB_LEFT_STICK_Y  1037
#define IDC_COMBO_EMUL_XB_RIGHT_STICK_X 1038
#define IDC_COMBO_EMUL_XB_RIGHT_STICK_Y 1039
#define IDC_COMBO_EMUL_XB_DPAD_X        1040
#define IDC_COMBO_EMUL_XB_DPAD_Y        1041
#define IDC_COMBO_EMUL_GC_LEFT_STICK_X  1042
#define IDC_COMBO_EMUL_GC_LEFT_STICK_Y  1043
#define IDC_COMBO_EMUL_GC_RIGHT_STICK_X 1044
#define IDC_COMBO_EMUL_GC_RIGHT_STICK_Y 1045
#define IDC_COMBO_EMUL_GC_DPAD_X        1046
#define IDC_COMBO_EMUL_GC_DPAD_Y        1047
#define IDC_COMBO_MODE                  1048
#define IDC_DEV_OPTIONS                 1049
#define IDC_DISPLAY_FPS                 1050
#define IDC_EDIT_PRINTBOX               1051
#define IDC_FILENAME                    1052
#define IDC_FILETYPE_COMBO              1053
#define IDC_FILE_LIST                   1054
#define IDC_GAMECUBE                    1055
#define IDC_HARD_DRIVE                  1056
#define IDC_INPUT_NAME                  1057
#define IDC_JPEG                        1058
#define IDC_MASTER_FILE                 1059
#define IDC_MASTER_FILENAME             1060
#define IDC_MASTER_FILE_TEXT            1061
#define IDC_MEMCARD_DIR                 1062
#define IDC_PLAYBACK_TEXT               1063
#define IDC_RADIO_EMUL_XB_RESET         1064
#define IDC_RADIO_EMUL_XB_START         1065
#define IDC_RADIO_EMUL_XB_BACK          1066
#define IDC_RADIO_EMUL_XB_BLACK         1067
#define IDC_RADIO_EMUL_XB_WHITE         1068
#define IDC_RADIO_EMUL_XB_A             1069
#define IDC_RADIO_EMUL_XB_B             1070
#define IDC_RADIO_EMUL_XB_X             1071
#define IDC_RADIO_EMUL_XB_Y             1072
#define IDC_RADIO_EMUL_XB_LEFT_TRIGGER  1073
#define IDC_RADIO_EMUL_XB_RIGHT_TRIGGER 1074
#define IDC_RADIO_EMUL_XB_LEFT_STICK    1075
#define IDC_RADIO_EMUL_XB_RIGHT_STICK   1076
#define IDC_RADIO_EMUL_GC_RESET         1077
#define IDC_RADIO_EMUL_GC_START         1078
#define IDC_RADIO_EMUL_GC_A             1079
#define IDC_RADIO_EMUL_GC_B             1080
#define IDC_RADIO_EMUL_GC_X             1081
#define IDC_RADIO_EMUL_GC_Y             1082
#define IDC_RADIO_EMUL_GC_Z             1083
#define IDC_RADIO_EMUL_GC_LEFT_TRIGGER_A 1084
#define IDC_RADIO_EMUL_GC_RIGHT_TRIGGER_A 1085
#define IDC_RADIO_EMUL_GC_RIGHT_TRIGGER_D 1086
#define IDC_RADIO_EMUL_GC_LEFT_TRIGGER_D 1087
#define IDC_RADIO_EMUL_XB_LEFT_STICK_X  1088
#define IDC_RADIO_EMUL_XB_LEFT_STICK_Y  1089
#define IDC_RADIO_EMUL_XB_RIGHT_STICK_X 1090
#define IDC_RADIO_EMUL_XB_RIGHT_STICK_Y 1091
#define IDC_RADIO_EMUL_XB_DPAD_X        1092
#define IDC_RADIO_EMUL_XB_DPAD_Y        1093
#define IDC_RADIO_EMUL_GC_LEFT_STICK_X  1094
#define IDC_RADIO_EMUL_GC_LEFT_STICK_Y  1095
#define IDC_RADIO_EMUL_GC_RIGHT_STICK_X 1096
#define IDC_RADIO_EMUL_GC_RIGHT_STICK_Y 1097
#define IDC_RADIO_EMUL_GC_DPAD_X        1098
#define IDC_RADIO_EMUL_GC_DPAD_Y        1099
#define IDC_RADIO_HARDWARE              1100
#define IDC_RADIO_REFRAST               1101
#define IDC_RADIO_SOFTWARE              1102
#define IDC_REALTIME_FPS                1103
#define IDC_RUNTIME_OPTIONS_FRAME       1104
#define IDC_SCREENSHOT_DIR              1105
#define IDC_SCREENSHOT_PATH_TEXT        1106
#define IDC_SCREEN_SHOT_OPTIONS         1107
#define IDC_SCREEN_SHOT_TEXT            1108
#define IDC_SERIES                      1109
#define IDC_SINGLE                      1110
#define IDC_SKIP_LEVEL_SELECT           1111
#define IDC_SLOT1                       1112
#define IDC_SLOT2                       1113
#define IDC_TGA                         1114
#define IDC_VERSION                     1115
#define IDC_VIDEO_MODE                  1116
#define IDC_VIEW_BOUNDS                 1117
#define IDC_WORLD_FILE_TEXT             1118
#define IDC_XBOX                        1119
#define IDC_DISPLAY_SAFE_SCREEN_BOX     1120
#define IDC_INSTALL_AUDIO               1121
#define IDC_CBDEBUG_AI                  1122
#define IDC_CBPLAYER_DEATH              1123
#define IDC_CBBDADAI                    1124
#define IDC_CHECK_SHOW_ENTITY_INFO      1125
#define IDC_DONT_DRAW_HUD               1126
#define IDC_DONT_DRAW_HUD2              1127
#define IDC_DONT_DRAW_DEBUG             1127
#define IDC_DONT_RENDER_SURFACE         1128
#define IDC_DONT_RENDER_SPECULAR        1129
#define IDC_DONT_RENDER_TRANSLUCENCIES  1130
#define IDC_LEGSERVO_DEFAULT            1131
#define IDC_LEGSERVO_L1                 1132
#define IDC_LEGSERVO_L2                 1133
#define IDC_LEGSERVO_L3                 1134
#define IDC_ARMSERVO_DEFAULT            1135
#define IDC_ARMSERVO_L1                 1136
#define IDC_ARMSERVO_L2                 1137
#define IDC_ARMSERVO_L3                 1138
#define IDC_DONT_DRAW_HUD3              1139
#define IDC_CAMERA_POV_VISIBILITY       1139
#define IDC_CAMERA_POV_VISIBILITY2      1140
#define IDC_LIGHT_SHOWRANGE             1140

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
