//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by K9.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_K9_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDD_VIDMODE                     129
#define IDD_ASSET_PICKER                130
#define IDR_MAITOOLBAR                  131
#define IDR_GRAPHTOOLBAR                133
#define IDB_BITMAP1                     136
#define IDR_GRAPHTESTTOOLBAR            137
#define IDR_GRAPHTOOLBAR3D              138
#define IDD_EDGEPROPS                   139
#define IDD_VERTPROPS                   140
#define IDD_QUERYCONFIG                 141
#define IDD_STRINGINPUT                 142
#define IDD_POIPROPS                    145
#define IDD_DIALOG1                     146
#define IDC_VIDEO_MODE                  1000
#define IDC_RADIO_HARDWARE              1000
#define IDC_RADIO_SOFTWARE              1001
#define IDC_RADIUS                      1001
#define IDC_RADIO_REFRAST               1002
#define IDC_3D_COLOR                    1002
#define IDC_FILETYPE_COMBO              1002
#define IDC_DRAW_STATS                  1003
#define IDC_FILENAME                    1003
#define IDC_FILE_LIST                   1004
#define IDC_DRAW_FPS                    1004
#define IDC_CHECKJUMP                   1004
#define IDC_ART_DIR                     1005
#define IDC_MASTER_FILENAME             1005
#define IDC_EBVERTID                    1005
#define IDC_CHECKDOOR                   1005
#define IDC_CHECK_FULLSCREEN            1006
#define IDC_DISPLAY_LIST_DIR            1006
#define IDC_CHECKLIFT                   1006
#define IDC_CHOOSE_ART_DIR              1007
#define IDC_EBHAZARDID                  1007
#define IDC_CHOOSE_DISPLAY_LIST_DIR     1008
#define IDC_SELECTHAZARDBUTTON          1008
#define IDC_DRAW_CAM_STATS              1009
#define IDC_CREVACE                     1009
#define IDC_INPUT_NAME                  1010
#define IDC_COMBO_DEVICE                1010
#define IDC_CUSTOMVOL                   1010
#define IDC_COMBO_MODE                  1011
#define IDC_BUTTON_RUN                  1011
#define IDC_BUTTON_SAVE                 1012
#define IDC_EBWIDTH                     1012
#define IDC_BUTTON_DEFAULT              1013
#define IDC_EBHEIGHT                    1013
#define IDC_EBQUERYWIDTH                1013
#define IDC_DRAW_LEAF_STATS             1014
#define IDC_EBQUERYHEIGHT               1014
#define IDC_SCREENSHOT_DIR              1015
#define IDC_CANJUMP                     1015
#define IDC_CHOOSE_SCREENSHOT_DIR       1016
#define IDC_3DMOVER                     1016
#define IDC_SERIES                      1017
#define IDC_BNEWSAVE                    1017
#define IDC_EDIT_PRINTBOX               1018
#define IDC_BUTTON_LOAD                 1019
#define IDC_BDELETESAVE                 1019
#define IDC_SINGLE                      1020
#define IDC_HIDE_CURSOR                 1021
#define IDC_CBSAVES                     1021
#define IDC_TGA                         1022
#define IDC_EBSTRING                    1022
#define IDC_JPEG                        1023
#define IDC_DROPOFF                     1025
#define IDC_VERSION                     1026
#define IDC_EBQUERYSLOPECOST            1026
#define IDC_UPONLY                      1026
#define IDCB_OFFENSIVEPOI               1028
#define IDCB_N                          1029
#define IDC_NE                          1030
#define IDC_E                           1031
#define IDC_SE                          1032
#define IDC_S                           1033
#define IDC_SCREENSHOT_PATH_TEXT        1034
#define IDC_SW                          1034
#define IDC_W                           1035
#define IDC_NW                          1036
#define IDCB_CUSTOM                     1037
#define IDRB_SHORTRANGE                 1038
#define IDRB_MEDRANGE                   1039
#define IDRB_LONGRANGE                  1040
#define IDC_SURFACEMOVER                1042
#define IDC_BRIDGE                      1043
#define IDC_DESTRUCT                    1044
#define IDC_JUMPTYPECOMBO               1045
#define IDC_HAZARDCOMBO                 1046
#define IDC_SCREEN_SHOT_OPTIONS         1050
#define IDC_SCREEN_SHOT_TEXT            1051
#define ID_SELECTTOOL                   32771
#define ID_ADDJOIN                      32772
#define ID_ADDONLY                      32773
#define ID_GRAPHTOOLBUTTON              32774
#define ID_JOIN                         32775
#define ID_OTHERTOOLBUTTON              32776
#define ID_UNJOIN                       32776
#define ID_SAVEBUTTON                   32778
#define ID_VIEWVOLUMES                  32779
#define ID_CALCVOLS                     32780
#define ID_AUTOJOIN                     32781
#define ID_GRAPHTESTBUTTON              32782
#define ID_ORIGINBUTTON                 32783
#define ID_GOALBUTTON                   32784
#define ID_FINDPATHBUTTON               32785
#define ID_RANDOMBUTTON                 32786
#define ID_CONFIGBUTTON                 32786
#define ID_VIEWEDGEVOLS                 32787
#define ID_UNDOBUTTON                   32790
#define ID_MOVE3DTOOL                   32791
#define ID_VIEWCUSTOMVOLS               32792
#define ID_VIEWNEARVOLS                 32793
#define ID_VIEWALLVOLS                  32794
#define ID_3DGRAPHTOOLBUTTON            32796
#define ID_3DMOVE3DTOOL                 32800
#define ID_3DADDJOIN                    32801
#define ID_3DJOIN                       32802
#define ID_3DUNJOIN                     32803
#define ID_3DSAVEBUTTON                 32804
#define ID_3DUNDOBUTTON                 32805
#define ID_3DVIEWVOLUMES                32806
#define ID_3DVIEWEDGEVOLS               32807
#define ID_3DVIEWALLVOLS                32808
#define ID_3DVIEWNEARVOLS               32809
#define ID_3DVIEWCUSTOMVOLS             32810
#define ID_MANMODE                      32811
#define ID_POI                          32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
