//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pasm2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PASM2_DIALOG                102
#define IDD_PASM_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_COMPILE_DIALOG              129
#define IDD_SETTINGS_DIALOG             130
#define IDR_MAIN_MENU                   132
#define IDR_POPUP_MENU                  133
#define IDD_SYNC_DIALOG                 134
#define IDD_ENTER_STRING_DLG            135
#define IDD_DELETE_FILE_DIALOG          136
#define IDD_ASSET_SCAN_DIALOG           140
#define ID_TOOLS_GENERATE_FILE_USAGE_FILE 141
#define ID_TOOLS_GENERATE_MASTER_FILE_LIST 142
#define ID_TOOLS_CREATENEWMASTERFILEWITHONLYLOGGEDASSETS 143
#define ID_TOOLS_GENERATELISTOFUNUSEDASSETS 144
#define ID_Menu                         145
#define ID_TOOLS_OPTIMIZEINTERNATIONALMASTERFILE 146
#define IDC_MASTER_FILE                 1000
#define IDC_CONFIG_FILE                 1001
#define IDC_CONFIG                      1004
#define IDC_MASTER_FILE_DIR             1005
#define IDC_CLEAR_ERROR_LOG             1005
#define IDC_XB_MASTER_FILE_DIR          1005
#define IDC_SYNC_DOWN_ALL_CHECK         1006
#define IDC_OPTIMIZE_MASTERFILE         1006
#define IDC_GC_MASTER_FILE_DIR          1006
#define IDC_EXTRACT                     1007
#define IDC_CHOOSE_MASTER_FILE_DIR      1007
#define IDC_CHOOSE_XB_MASTER_FILE_DIR   1007
#define IDC_CHOOSE_GC_MASTER_FILE_DIR   1008
#define IDC_LOCAL_DIR                   1009
#define IDC_FILENAME                    1009
#define IDC_LIB_DIR                     1010
#define IDC_XBOX_FORMAT                 1010
#define IDC_FROM_LIB                    1010
#define IDC_AUTO_DOWNSIZE_TEXTURES      1010
#define IDC_CHOOSE_LIB_DIR              1011
#define IDC_PC_FORMAT                   1011
#define IDC_FROM_LOCAL                  1011
#define IDC_DONT_GENERATE_STRIPS        1011
#define IDC_DISABLE_STRIPPING           1011
#define IDC_AUTO_DOWNSIZE_TEXTURES2     1011
#define IDC_CHOOSE_LOCAL_DIR            1012
#define IDC_FROM_MASTER                 1012
#define IDC_DISABLE_STRIPPING2          1012
#define IDC_DETAILED_LIGHTING_INFO      1012
#define IDC_LIBRARY_LOCK_DIR            1013
#define IDC_CREATE_NEW_CONFIG_NAME      1014
#define IDC_CHOOSE_MASTER_FILE          1015
#define IDC_IGNORE_EXTENSIONS           1016
#define IDC_CREATE_NEW_MASTER_NAME      1017
#define IDC_CURRENT_FILENAME            1018
#define IDC_CHOOSE_CONFIG_FILE          1018
#define IDC_CHOOSE_LIB_LOCK_DIR         1019
#define IDC_OUTPUT_DEBUG_PICS_CHECK     1020
#define IDC_XCLIENT_DIR                 1020
#define IDC_PROGRESS_BAR                1021
#define IDC_CHOOSE_XCLIENT_DIR          1021
#define IDC_LOG_OUTPUT_DIR              1024
#define IDC_LOCAL_COUNT                 1024
#define IDC_CLICK_ANYWHERE              1024
#define IDC_CHOOSE_LOG_OUTPUT_DIR       1025
#define IDC_MASTER_FILE_COUNT           1025
#define IDC_ABORT                       1025
#define IDC_VERSION                     1026
#define IDC_CHOOSE_EXTRACT_DIR          1026
#define IDC_EXTRACT_DIR                 1027
#define IDC_LIB_COUNT                   1027
#define IDC_CONFIG_DIR                  1028
#define IDC_DISPLAY_COUNT               1028
#define IDC_CHOOSE_CONFIG_DIR           1029
#define IDC_AUTO_RUN_XCLIENT            1030
#define IDC_STATIC_INSTRUCTIONS         1033
#define IDC_INPUT_USER_STRING           1034
#define IDC_FILE_LIST                   1038
#define IDC_SLIDER1                     1039
#define IDC_SHOW_DIFF                   1040
#define IDC_SHOW_FILESTATS              1040
#define IDC_LMAP_MAXSIZE                1040
#define IDC_HIDE_NONCOMPILABLE_FILES    1041
#define IDC_FILTER                      1041
#define IDC_OP_TEXT                     1042
#define IDC_SUBOP_TEXT                  1043
#define IDC_OP_PROGRESS                 1044
#define IDC_SUBOP_PROGRESS              1045
#define IDC_COMPILE_RESULTS             1050
#define IDC_RICHEDIT21                  1051
#define IDC_EDIT1                       1053
#define IDC_SUBSAMPLE                   1053
#define IDC_DONT_USE_VIS                1055
#define IDC_SLIDER2                     1056
#define IDC_DONT_USE_VIS2               1056
#define IDC_REUSE_PERFECT_MATCH_ONLY    1056
#define IDC_CHECK1                      1057
#define IDC_REBUILD_MASTER_FILE         1059
#define IDC_SCAN_PROGRESS_BAR           1059
#define IDC_RESCAN                      1060
#define IDC_SCAN_AND_COMPILE            1061
#define IDC_SYNC_DOWN_AND_COMPILE       1062
#define IDC_SLIDER3                     1063
#define IDC_DELETE                      1080
#define IDC_DELETE_ALL                  1081
#define IDC_COMPILE                     1084
#define IDC_SYNC_UP                     1085
#define IDC_SYNC_DOWN                   1086
#define IDC_DUMP_FILENAMES              1087
#define IDC_NEWER_THAN_LOCAL            1090
#define IDC_NEWER_THAN_LIB              1092
#define IDC_NEWER_THAN_MASTER           1093
#define IDC_MAIN_STATUSBAR              32500
#define IDC_PROGRESS_STATUSBAR          32501
#define ID_PLATFORM_XBOX                32779
#define ID_PLATFORM_PC                  32781
#define ID_VIEW_SHOWDIFFERENCESONLY     32782
#define ID_VIEW_HIDE_NON_COMPILABLE_FILES 32783
#define ID_VIEW_HOLD_COMPILE_STATS      32784
#define IDC_MIRROR_LIBRARY              32785
#define ID_DISABLE_LIB                  32786
#define ID_OPEN_ERRORLOG                32787
#define ID_TOOLS_CREATE_ZIP_FILE        32788
#define ID_PLATFORM_GC                  32789
#define ID_OUTPUT_DEBUG_PICS            32790
#define IDC_FORCE_COMPILE               32791
#define IDC_COMPACT_MASTER_FILE         32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
