//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Spit.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SPIT_DIALOG                 102
#define IDD_VIDMODE                     103
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define ID_FILE_UPDATEVERSION           130
#define IDD_ASSET_PICKER                131
#define IDD_NUM_PARTICLES               132
#define IDD_FORCES                      133
#define IDD_LIFESPAN                    134
#define IDD_LOD                         135
#define IDD_LIGHT                       136
#define IDD_SPRITES                     137
#define IDD_SCALE                       138
#define IDD_COLOR                       139
#define IDD_EMISSIVE                    140
#define IDD_POSITION                    141
#define IDD_VELOCITY                    142
#define IDD_GLOBAL                      143
#define IDC_STATIC_FRAME                1000
#define IDC_NO_TIMELIMIT                1001
#define IDC_FILETYPE_COMBO              1002
#define IDC_BURST_FOREVER               1004
#define IDC_EDIT_GRAVITY                1005
#define IDC_SPIKE_ALPHA_ON              1005
#define IDC_FILENAME                    1006
#define IDC_MULTI_SPRITES               1007
#define IDC_EDIT_DRAG                   1008
#define IDC_MULTI_SPRITES2              1008
#define IDC_CLOSE_SPRITES_GAP           1008
#define IDC_FILE_LIST                   1009
#define IDC_SAMPLE_LIGHTS               1010
#define IDC_RESET_GRAVITY               1011
#define IDC_MASTER_FILENAME             1012
#define IDC_PIXEL_SIZE                  1013
#define IDC_EDIT_ALPHA_PERCENT_PER_SPRITE 1014
#define IDC_RESET_DRAG                  1015
#define IDC_Z_BUFFER                    1016
#define IDC_EDIT_SIZE_PERCENT_PER_SPRITE 1017
#define IDC_Z_BUFFER2                   1017
#define IDC_SORT                        1017
#define IDC_EARTH_GRAVITY               1018
#define IDC_NO_FOG                      1019
#define IDC_EDIT_POS_PER_SPRITE         1020
#define IDC_DIRECTIONAL_EMISSION        1021
#define IDC_IGNORE_WIND                 1022
#define IDC_RADIO_MIN                   1023
#define IDC_JITTER_POS                  1023
#define IDC_ENABLE_TEXTURES             1024
#define IDC_RADIO_MAX                   1025
#define IDC_USE_BUBBLE_FORCE            1025
#define IDC_CHOOSE_TEXTURE              1026
#define IDC_BUTTON_SET_TO_DEFAULTS      1027
#define IDC_ENABLE_SOUND                1027
#define IDC_GROUP_Z_SCALE               1028
#define IDC_SPLIT_ON_IMPACT             1029
#define IDC_ONE_SHOT                    1030
#define IDC_EMIT_LIGHT                  1031
#define IDC_BUTTON_COPY_SETTINGS        1032
#define IDC_CHOOSE_CORONA_TEXTURE       1032
#define IDC_RADIO_MODULATE_MODE         1033
#define IDC_BUTTON_COPY_CURRENT_SETTINGS 1033
#define IDC_RADIO_ADD_MODE              1034
#define IDC_EDIT_CULL_DISTANCE          1035
#define IDC_CORONA_ON                   1035
#define IDC_EDIT_LOD_PERCENT            1036
#define IDC_CLEAR_CORONA_TEXTURE        1036
#define IDC_EDIT_RED                    1037
#define IDC_EDIT_LOD_EMULATIONDIST      1037
#define IDC_EDIT_EMULATION_DISTANCE     1037
#define IDC_PER_PIXEL_LIGHT_ON          1037
#define IDC_EDIT_GREEN                  1038
#define IDC_WORLD_SCALE_CORONA_ON       1038
#define IDC_EDIT_BLUE                   1039
#define IDC_AUTO_CALCULATE_LIGHT_INTENSITY_ON 1039
#define IDC_BUTTON_PICK_COLOR           1040
#define IDC_SPIKE_COLOR_ON              1040
#define IDC_VERSION                     1041
#define IDC_SPIKE_SCALE_ON              1041
#define IDC_EDIT_RED2                   1041
#define IDC_EDIT_INTENSITY              1042
#define IDC_EDIT_MAX_LIFE_SECS          1043
#define IDC_EDIT_GREEN2                 1043
#define IDC_TEST                        1044
#define IDC_EDIT_BLUE2                  1044
#define IDC_EDIT_RADIUS_PERCENT         1045
#define IDC_EDIT_MIN_LIFE_SECS          1046
#define IDC_BUTTON_PICK_COLOR2          1046
#define IDC_EDIT_NUM_SPRITES            1047
#define IDC_EDIT_INTENSITY2             1047
#define IDC_EDIT_FINAL_MIN_RED          1048
#define IDC_EDIT_RADIUS_PERCENT2        1048
#define IDC_EDIT_MAX_SPRITE_VEL         1049
#define IDC_EDIT_SOUND_VOL              1049
#define IDC_EDIT_INIT_MAX_RED           1050
#define IDC_EDIT_SOUND_PITCH            1050
#define IDC_EDIT_MIN_INIT_SCALE         1051
#define IDC_EDIT_MAX_RADIUS             1051
#define IDC_EDIT_INIT_MAX_GREEN         1052
#define IDC_EDIT_MAX_INIT_SCALE         1053
#define IDC_EDIT_INIT_MAX_BLUE          1054
#define IDC_EDIT_MIN_FINAL_SCALE        1055
#define IDC_BUTTON_PICK_MAX_INIT_COLOR  1056
#define IDC_RANDOM_INIT_COLOR           1057
#define IDC_EDIT_MAX_FINAL_SCALE        1058
#define IDC_EDIT_FINAL_MIN_GREEN        1059
#define IDC_RANDOM_FINAL_COLOR          1060
#define IDC_EDIT_FINAL_MIN_BLUE         1061
#define IDC_BUTTON_PICK_MIN_FINAL_COLOR 1062
#define IDC_EDIT_FINAL_MAX_RED          1063
#define IDC_EDIT_FINAL_MAX_GREEN        1064
#define IDC_EDIT_FINAL_MAX_BLUE         1065
#define IDC_BUTTON_PICK_MAX_FINAL_COLOR 1066
#define IDC_BUTTON_PICK_MIN_INIT_COLOR  1067
#define IDC_EDIT_BURSTS_PER_SEC         1068
#define IDC_EDIT_MIN_BURSTS_PER_SEC     1068
#define IDC_EDIT_INIT_MIN_ALPHA         1069
#define IDC_EDIT_MAX_BURSTS_PER_SEC     1069
#define IDC_EDIT_SECS_TO_EMIT           1070
#define IDC_EDIT_FINAL_MIN_ALPHA        1071
#define IDC_EDIT_MIN_DELAY_SECS         1071
#define IDC_EDIT_MIN_PARTICLES          1072
#define IDC_EDIT_INIT_MAX_ALPHA         1073
#define IDC_EDIT_MIN_DELAY_SECS2        1073
#define IDC_EDIT_MAX_DELAY_SECS         1073
#define IDC_EDIT_RAND_PARTICLES         1074
#define IDC_EDIT_MAX_PARTICLES          1075
#define IDC_EDIT_FINAL_MAX_ALPHA        1076
#define IDC_EDIT_INIT_MIN_RED           1077
#define IDC_EDIT_INIT_MIN_GREEN         1078
#define IDC_EDIT_INIT_MIN_BLUE          1079
#define IDC_EDIT_MIN_EMISSIVE           1080
#define IDC_RADIO_HARDWARE              1081
#define IDC_EDIT_MAX_EMISSIVE           1082
#define IDC_RADIO_SOFTWARE              1083
#define IDC_EDIT_INITIAL_POS_RADIUS     1084
#define IDC_RADIO_REFRAST               1085
#define IDC_EDIT_JITTER_X               1085
#define IDC_EDIT_MIN_INIT_VEL           1086
#define IDC_EDIT_JITTER_Y               1086
#define IDC_COMBO_DEVICE                1087
#define IDC_EDIT_JITTER_Z               1087
#define IDC_EDIT_MAX_INIT_VEL           1088
#define IDC_COMBO_MODE                  1089
#define IDC_EDIT_MIN_SPREAD_ANGLE       1090
#define IDC_EDIT_MAX_SPREAD_ANGLE       1091
#define IDC_CHECK_PAUSE                 1092
#define IDC_BUTTON_EMIT_SHOT            1093
#define IDC_EDIT_EMIT_Y                 1094
#define IDC_EDIT_EMIT_ROT               1095
#define IDC_EDIT_EMIT_INTENSITY         1096
#define IDC_STATS                       1097
#define IDC_CHECK_DRAW_BOUNDING_SPHERE  1098
#define IDC_TEXTURE_NAME                1099
#define IDC_BUTTON_STOP                 1099
#define IDC_CHECK_SLOW_MO               1100
#define IDC_SOUND_NAME                  1100
#define IDC_CHECK_DRAW_AID              1101
#define IDC_CORONA_TEXTURE_NAME         1101
#define IDC_CHECK_LOOK_AT_CAMERA        1102
#define IDC_STATIC_VIEWFRAME            1103
#define IDC_TILT                        1104
#define IDC_CHECK_DRAW_LIGHT_BS         1104
#define IDC_TILT_SPIN                   1105
#define IDC_CHECK_AMBIENT_LIGHT_ON      1105
#define IDC_EDIT_MOTIF_INDEX            1106
#define IDC_EDIT_SAMPLES_PER_SEC        1107
#define IDC_BUTTON_PICK_AMBIENT_LIGHT   1107
#define IDC_EDIT_SCALE_SAMPLED_RED      1108
#define IDC_EDIT_BUBBLE_X               1108
#define IDC_EDIT_SCALE_SAMPLED_GREEN    1109
#define IDC_EDIT_BUBBLE_Y               1109
#define IDC_EDIT_SCALE_SAMPLED_BLUE     1110
#define IDC_EDIT_BUBBLE_Z               1110
#define IDC_EDIT_BUBBLE_UPDATE_CHANCE   1111
#define IDC_EDIT_CORONA_SCALE           1111
#define IDC_EDIT_BUBBLE_DRAG            1112
#define IDC_MAKE_INTENSITY_EQUAL        1113
#define IDC_MAKE_RADIUS_MULTIPIER_EQUAL 1114
#define IDC_MAKE_INIT_COLORS_EQUAL      1114
#define IDC_MAKE_LIGHT_COLORS_EQUAL     1115
#define IDC_MAKE_FINAL_COLORS_EQUAL     1116
#define IDC_MAKE_INIT_ALPHA_EQUAL       1117
#define IDC_MAKE_FINAL_ALPHA_EQUAL      1118
#define ID_NEW_FILE                     32771
#define ID_OPEN_FILE                    32772
#define ID_SAVE_FILE                    32773
#define ID_SAVEAS                       32774
#define ID_SELECT_MASTERFILE            32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
