"""Assemble Fang's Direct3D 8 shader sources into C headers.

The original build used Microsoft's vsa/psa assemblers (DirectX 8 SDK) to turn
the .nvv (vertex) and .nvp (pixel) sources into CompiledVShader*.h /
CompiledPShader*.h. Those tools and their outputs are not in the source drop,
so this reproduces them with the D3D assembler that ships with Windows
(d3dcompiler_47.dll, D3DAssemble).

Usage: build_shaders.py <fang2/dx source dir> <output dir>

Outputs, per source file <name>.nvv / <name>.nvp:
    CompiledVShader<name>.h   const DWORD dw<Name>VertexShader[] = {...};
    CompiledPShader<name>.h   const DWORD dw<Name>PixelShader[]  = {...};
where <Name> is <name> with its first letter upper-cased (vsa/psa convention).
Also: win/fdxsh_psprite.cvs from fdxsh_psprite.vsh (compiled vertex shader).
"""
import ctypes, os, re, sys
from ctypes import wintypes

d3dc = ctypes.WinDLL("d3dcompiler_47")
_assemble = d3dc.D3DAssemble
_assemble.restype = ctypes.c_long
_assemble.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_char_p, ctypes.c_void_p,
                      ctypes.c_void_p, ctypes.c_uint,
                      ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(ctypes.c_void_p)]

_GetPtr = ctypes.WINFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p)
_GetSize = ctypes.WINFUNCTYPE(ctypes.c_size_t, ctypes.c_void_p)
_Release = ctypes.WINFUNCTYPE(ctypes.c_ulong, ctypes.c_void_p)


def _vtbl(iface, idx, ftype):
    vtable = ctypes.cast(iface, ctypes.POINTER(ctypes.POINTER(ctypes.c_void_p)))[0]
    return ftype(vtable[idx])


def blob_bytes(blob):
    ptr = _vtbl(blob, 3, _GetPtr)(blob)
    size = _vtbl(blob, 4, _GetSize)(blob)
    return ctypes.string_at(ptr, size)


def blob_release(blob):
    if blob:
        _vtbl(blob, 2, _Release)(blob)


_define_re = re.compile(r'^\s*#\s*define\s+([A-Za-z_]\w*)(?:\s+(.*))?$')
_include_re = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def preprocess(path, defines=None, seen=None):
    """Minimal preprocessor: #include "x" and object-like #define only."""
    if defines is None:
        defines = {}
    out = []
    text = open(path, encoding="latin1").read()
    for line in text.splitlines():
        m = _include_re.match(line)
        if m:
            inc = os.path.join(os.path.dirname(path), m.group(1))
            out.extend(preprocess(inc, defines))
            continue
        m = _define_re.match(line)
        if m:
            value = (m.group(2) or "").split(";")[0].split("//")[0].strip()
            defines[m.group(1)] = value
            continue
        out.append(line)
    return out


def expand(lines, defines):
    if not defines:
        return lines
    names = sorted(defines, key=len, reverse=True)
    rx = re.compile(r'\b(' + "|".join(re.escape(n) for n in names) + r')\b')
    result = []
    for line in lines:
        # split off ';' comments so macro names inside comments are left alone
        code, sep, comment = line.partition(";")
        for _ in range(16):
            new = rx.sub(lambda mm: defines[mm.group(1)], code)
            if new == code:
                break
            code = new
        result.append(code + sep + comment)
    return result


def assemble(path):
    defines = {}
    lines = expand(preprocess(path, defines), defines)
    src = "\n".join(lines) + "\n"
    # D3D9 requires vs_1_1 as the minimum vertex shader version; 1.0 code is valid 1.1.
    src = re.sub(r'(?im)^(\s*)vs\.1\.0\b', r'\1vs.1.1', src)
    # oFog / oPts are scalar registers in D3D9: DX8 syntax wrote them as oFog.x / oPts.x.
    src = re.sub(r'\b(oFog|oPts)\.[xyzw]\b', r'\1', src)

    data = src.encode("latin1")
    shader = ctypes.c_void_p()
    errors = ctypes.c_void_p()
    # D3DCOMPILE_SKIP_VALIDATION (2): vs_1_x inputs (v0..vN) are bound by the vertex
    # declaration at runtime and never declared in the source, which the strict
    # validator reports as reads of uninitialized registers.
    hr = _assemble(data, len(data), os.path.basename(path).encode(), None, None, 2,
                   ctypes.byref(shader), ctypes.byref(errors))
    if hr < 0 or not shader.value:
        msg = blob_bytes(errors).decode("latin1", "replace") if errors.value else "hr=0x%08x" % (hr & 0xffffffff)
        blob_release(errors)
        raise RuntimeError(msg.strip())
    code = blob_bytes(shader)
    blob_release(shader)
    blob_release(errors)
    return [int.from_bytes(code[i:i + 4], "little") for i in range(0, len(code), 4)]


def write_header(path, comment, ctype_name, words):
    with open(path, "w", newline="\n") as f:
        f.write("// %s\n// Generated by tools/build_shaders.py - do not edit.\n" % comment)
        f.write("const DWORD %s[] =\n{\n" % ctype_name)
        for i in range(0, len(words), 6):
            f.write("\t" + ", ".join("0x%08x" % w for w in words[i:i + 6]) + ",\n")
        f.write("};\n")


def cap(name):
    return name[0].upper() + name[1:]


def main(src_dir, out_dir):
    os.makedirs(os.path.join(out_dir, "win"), exist_ok=True)
    failures = []
    count = 0
    for fn in sorted(os.listdir(src_dir)):
        base, ext = os.path.splitext(fn)
        ext = ext.lower()
        if ext not in (".nvv", ".nvp") and fn.lower() != "fdxsh_psprite.vsh":
            continue
        try:
            words = assemble(os.path.join(src_dir, fn))
        except Exception as e:
            failures.append((fn, str(e)))
            continue
        if ext == ".nvv":
            write_header(os.path.join(out_dir, "CompiledVShader%s.h" % base), fn,
                         "dw%sVertexShader" % cap(base), words)
        elif ext == ".nvp":
            write_header(os.path.join(out_dir, "CompiledPShader%s.h" % base), fn,
                         "dw%sPixelShader" % cap(base), words)
        else:
            write_header(os.path.join(out_dir, "win", "fdxsh_psprite.cvs"), fn,
                         "dw%sVertexShader" % cap(base), words)
        count += 1
    print("assembled %d shaders, %d failed" % (count, len(failures)))
    for fn, msg in failures:
        print("FAILED %s:\n  %s" % (fn, msg.replace("\n", "\n  ")))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2]))
