"""Generate CMake source lists from the original Visual Studio project files.

Reads ma/Lib/Fang2/dx/win/fang2win.vcproj and ma/App/ma/win/ma_win.vcproj and
writes cmake/sources_fang2.cmake / cmake/sources_ma.cmake with paths relative
to the repo root (all sources live under ma/). Re-run only if the lists need
regenerating; the generated files are committed.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def project_sources(vcproj, exts):
    base = os.path.dirname(vcproj)
    t = open(vcproj, encoding="latin1").read()
    out = []
    for rel in re.findall(r'RelativePath="([^"]+)"', t):
        if not rel.lower().endswith(exts):
            continue
        p = os.path.normpath(os.path.join(base, rel.replace("\\", "/")))
        r = os.path.relpath(p, ROOT).replace("\\", "/")
        if r not in out:
            out.append(r)
    return out

def write_list(path, var, files, header):
    with open(path, "w", newline="\n") as f:
        f.write("# " + header.replace("\n", "\n# ") + "\n")
        f.write("set(%s\n" % var)
        for x in files:
            f.write("    %s\n" % x)
        f.write(")\n")

fang = project_sources(os.path.join(ROOT, "ma/Lib/Fang2/dx/win/fang2win.vcproj"), (".cpp", ".c", ".asm"))
ma   = project_sources(os.path.join(ROOT, "ma/App/ma/win/ma_win.vcproj"), (".cpp", ".c"))
missing = [x for x in fang + ma if not os.path.exists(os.path.join(ROOT, x))]
hdr = "Generated by tools/gen_sources.py from the original .vcproj. Do not hand-edit; use CMakeLists.txt to add/remove."
write_list(os.path.join(ROOT, "cmake/sources_fang2.cmake"), "FANG2_SOURCES", fang, hdr)
write_list(os.path.join(ROOT, "cmake/sources_ma.cmake"),    "MA_SOURCES",    ma,   hdr)
print("fang2 sources:", len(fang), " ma sources:", len(ma), " missing on disk:", len(missing))
for m in missing[:20]: print("  MISSING", m)
